[build]

publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.75.1"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
    command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"