[build]

publish = "public"
command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
    command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"